site_name: Goms
pages:
    - Home: index.md
    - Setting up: settingup.md
    - Entities: entities.md
    - Entity Relations: entity_relations.md
    - Users and groups: users_and_usergroups.md
    - Authorization: authorization.md
    - Actions: actions.md
    - Data storage: data_storage.md
    - Marketplace: marketplace.md
theme: readthedocs