site_name: Daptin
pages:
    - Home: index.md
    - Setting up: settingup.md
    - Entities: entities.md
    - Entity Relations: entity_relations.md
    - Users and groups: users_and_usergroups.md
    - Authorization: authorization.md
    - Actions: actions.md
    - Data storage: data_storage.md
    - Marketplace: marketplace.md
    - Data Auditing: auditing.md
    - Authentication: authentication.md
    - Data validation: data_validation.md
    - Data conformations: data_conformation.md
    - State tracking: state_tracking.md
    - Data Streams: streams.md
    - Permission model: permissions.md
    - OAuth Connections: oauth_connection.md
theme: material